name: Three Tier CI/CD

on:
  push:
    branches:
      - main

jobs:
  backend-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build backend
        working-directory: backend
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: mvn clean package -DskipTests

        - name: Copy WAR to backend EC2
  uses: appleboy/scp-action@v1
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ${{ secrets.EC2_USER }}
    key: ${{ secrets.EC2_SSH_KEY }}
    source: "backend/target/*.war"
    target: "/tmp/"
    strip_components: 2

- name: Deploy WAR to Tomcat
  uses: appleboy/ssh-action@v1
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ${{ secrets.EC2_USER }}
    key: ${{ secrets.EC2_SSH_KEY }}
    script: |
      sudo rm -f /opt/tomcat/webapps/backend-1.0.0.war
      sudo rm -rf /opt/tomcat/webapps/backend-1.0.0
      sudo mv /tmp/backend-1.0.0.war /opt/tomcat/webapps/
